// applicant-frontend/src/Components/Footer/Footer.jsx
'using strict';

import React, { Component } from 'react';
import './styles.css';
import { Container, Row, Col } from 'react-bootstrap';

import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faMobileAlt, faMapMarkerAlt, faEnvelope, faUserSecret } from '@fortawesome/free-solid-svg-icons';
import { fab } from '@fortawesome/free-brands-svg-icons';
import { library } from '@fortawesome/fontawesome-svg-core';

library.add(fab);

const TEXTS = require('../../texts.json').FOOTER;

class Footer extends Component {
  render() {
    return (
      <footer>
        <Container>
          <Row>
            <Col dangerouslySetInnerHTML={{ __html: TEXTS.FIRST_COLUMN }}>
            </Col>
            <Col>
              <ul>
                { TEXTS.EMAIL ? <li><FontAwesomeIcon className='footer-icon' icon={faEnvelope} /> {TEXTS.EMAIL }</li> : '' }
                { TEXTS.PHONE_NUMBER ? <li><FontAwesomeIcon className='footer-icon' icon={faMobileAlt} /> { TEXTS.PHONE_NUMBER }</li> : '' }
                { TEXTS.ADRESS ? <li><FontAwesomeIcon className='footer-icon' icon={faMapMarkerAlt} /> { TEXTS.ADRESS }</li> : '' }
                <li><FontAwesomeIcon className='footer-icon' icon={faUserSecret} /><a href='/privacy-policy/'>Privacy Policy</a></li>
              </ul>
              <div className='social-media-box'>
                {
                  TEXTS.YOUTUBE ?
                  <a href={TEXTS.YOUTUBE} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'youtube']}/>
                  </a>
                  :
                  ''
                }
                {
                  TEXTS.FACEBOOK ?
                  <a href={TEXTS.FACEBOOK} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'facebook']}/>
                  </a>
                  :
                  ''
                }
                {
                  TEXTS.INSTAGRAM ?
                  <a href={TEXTS.INSTAGRAM} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'instagram']}/>
                  </a>
                  :
                  ''
                }
                {
                  TEXTS.LINKEDIN ?
                  <a href={TEXTS.LINKEDIN} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'linkedin']}/>
                  </a>
                  :
                  ''
                }
                {
                  TEXTS.GITHUB ?
                  <a href={TEXTS.GITHUB} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'github']}/>
                  </a>
                  :
                  ''
                }
                {
                  TEXTS.TWITTER ?
                  <a href={TEXTS.TWITTER} target='_blank' rel='noopener noreferrer'>
                    <FontAwesomeIcon className='social-media-icon' icon={['fab', 'twitter']}/>
                  </a>
                  :
                  ''
                }
              </div>
            </Col>
            <Col>
              Platform developed by <a href='https://socialhackersacademy.org/' target='_blank' rel='noopener noreferrer'> Social Hackers Academy </a> under
              <a href='https://github.com/Marc-AntoineA/A2P/blob/master/LICENSE' target='_blank' rel='noopener noreferrer'> MIT Licence </a>
              (Source code <a href='https://github.com/Marc-AntoineA/A2P' target='_blank' rel='noopener noreferrer'>
                <FontAwesomeIcon className='social-media-icon' icon={['fab', 'github']}/>
              </a>).<br/>
              Version {this.props.version}
            </Col>
          </Row>
        </Container>
      </footer>
    );
  }
}

export default Footer;

// superviser-frontend/src/components/Footer.vue
<template>
  <el-footer>
    <el-row>
      <el-col :span="8">
        <p>
          Platform developed by
            <a href='https://socialhackersacademy.org/' target='_blank' rel='noopener noreferrer'>Social Hackers Academy</a>.
        </p>
        <p>
          <font-awesome-icon class='big-icon' :icon="['fab', 'github']" />
          <a href='https://github.com/Marc-AntoineA/A2P' target='_blank' rel='noopener noreferrer'>Source Code</a>
          (under
            <a href='https://github.com/Marc-AntoineA/A2P/blob/master/LICENSE' target='_blank' rel='noopener noreferrer'>
              MIT Licence
            </a>
          )
        </p>
        <p> <!-- TODO compute it from package.json -->
          Version 1.0.0-dev
        </p>
      </el-col>
      <el-col :span="8">
        <ul class='links-list'>
          <li>
            <span class='link-prefix'>Go to</span>
            <a href='https://socialhackersacademy.org/'>Social Hackers Academy Website</a>
          </li>
          <li><span class='link-prefix'>Go to</span> <a href='/'> Applicant Website</a></li>
        </ul>
      </el-col>
      <el-col :span="8">
        <p>
          Questions? Problems? Ideas?
          <a href='https://github.com/Marc-AntoineA/A2P/issues' target='_blank' rel='noopener noreferrer'>Open an issue</a>.
        </p>
      </el-col>
    </el-row>
  </el-footer>
</template>

<script>
import { library } from '@fortawesome/fontawesome-svg-core';
import { faGithub } from '@fortawesome/free-brands-svg-icons'
library.add(faGithub);

export default {
  name: 'aap-footer',
  props: [],
}
</script>

<style>
.el-footer {
	border-top: solid 4px teal;
	margin: -8px;
	margin-top: 20px;
	padding: 20px 0px;
}

.big-icon {
  font-size: 40px;
}

.links-list {
  list-style: none;
  text-align: left;
}

.link-prefix {
	text-transform: uppercase;
	font-weight: bolder;
	color: #303030;
	font-size: 12px;
	margin-right: 7px;
}
</style>
